package cursoNTecnologias.bd.domain;

public class DetalleVentas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detalle_ventas.ventaId
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private Integer ventaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detalle_ventas.productoId
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private Integer productoid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column detalle_ventas.cantidad
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private Integer cantidad;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detalle_ventas.ventaId
     *
     * @return the value of detalle_ventas.ventaId
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    
    private Productos producto;
    
    public DetalleVentas() {
    	setProducto(new Productos ());
    }
    
    public Productos getProducto() {
		return producto;
	}

	public void setProducto(Productos producto) {
		this.producto = producto;
	}

    
    public Integer getVentaid() {
        return ventaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detalle_ventas.ventaId
     *
     * @param ventaid the value for detalle_ventas.ventaId
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setVentaid(Integer ventaid) {
        this.ventaid = ventaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detalle_ventas.productoId
     *
     * @return the value of detalle_ventas.productoId
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public Integer getProductoid() {
        return productoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detalle_ventas.productoId
     *
     * @param productoid the value for detalle_ventas.productoId
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setProductoid(Integer productoid) {
        this.productoid = productoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column detalle_ventas.cantidad
     *
     * @return the value of detalle_ventas.cantidad
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public Integer getCantidad() {
        return cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column detalle_ventas.cantidad
     *
     * @param cantidad the value for detalle_ventas.cantidad
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    
    @Override
    public String toString () {
    	String str = "";
    	str += "ventaId: " + ventaid + "\n";
    	str += "productoId: " + productoid + "\n";
    	str += "cantidad: " + cantidad + "\n";
    	return str;
    }
}