package cursoNTecnologias.bd.domain;

public class Direccion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direccion.idDireccion
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private Integer iddireccion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direccion.calle
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private String calle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direccion.numero
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private Integer numero;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direccion.colonia
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private String colonia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direccion.ciudad
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private String ciudad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direccion.estado
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private String estado;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direccion.pais
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private String pais;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direccion.codigoPostal
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private Integer codigopostal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direccion.idDireccion
     *
     * @return the value of direccion.idDireccion
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public Integer getIddireccion() {
        return iddireccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direccion.idDireccion
     *
     * @param iddireccion the value for direccion.idDireccion
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setIddireccion(Integer iddireccion) {
        this.iddireccion = iddireccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direccion.calle
     *
     * @return the value of direccion.calle
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public String getCalle() {
        return calle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direccion.calle
     *
     * @param calle the value for direccion.calle
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setCalle(String calle) {
        this.calle = calle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direccion.numero
     *
     * @return the value of direccion.numero
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public Integer getNumero() {
        return numero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direccion.numero
     *
     * @param numero the value for direccion.numero
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setNumero(Integer numero) {
        this.numero = numero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direccion.colonia
     *
     * @return the value of direccion.colonia
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public String getColonia() {
        return colonia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direccion.colonia
     *
     * @param colonia the value for direccion.colonia
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direccion.ciudad
     *
     * @return the value of direccion.ciudad
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public String getCiudad() {
        return ciudad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direccion.ciudad
     *
     * @param ciudad the value for direccion.ciudad
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direccion.estado
     *
     * @return the value of direccion.estado
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public String getEstado() {
        return estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direccion.estado
     *
     * @param estado the value for direccion.estado
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setEstado(String estado) {
        this.estado = estado;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direccion.pais
     *
     * @return the value of direccion.pais
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public String getPais() {
        return pais;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direccion.pais
     *
     * @param pais the value for direccion.pais
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setPais(String pais) {
        this.pais = pais;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direccion.codigoPostal
     *
     * @return the value of direccion.codigoPostal
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public Integer getCodigopostal() {
        return codigopostal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direccion.codigoPostal
     *
     * @param codigopostal the value for direccion.codigoPostal
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setCodigopostal(Integer codigopostal) {
        this.codigopostal = codigopostal;
    }
}