package cursoNTecnologias.bd.domain;

import java.util.Date;

public class Ganancias {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ganancias.idGanancia
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private Integer idganancia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ganancias.ventaId
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private Integer ventaid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ganancias.totalGanancia
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private Double totalganancia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ganancias.fecha
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private Date fecha;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ganancias.idGanancia
     *
     * @return the value of ganancias.idGanancia
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    
    private Ventas venta;
    
    public Ganancias () {
    	setVenta(new Ventas ());
    }
    
    public Ventas getVenta() {
		return venta;
	}

	public void setVenta(Ventas venta) {
		this.venta = venta;
	}

	public Integer getIdganancia() {
        return idganancia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ganancias.idGanancia
     *
     * @param idganancia the value for ganancias.idGanancia
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setIdganancia(Integer idganancia) {
        this.idganancia = idganancia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ganancias.ventaId
     *
     * @return the value of ganancias.ventaId
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public Integer getVentaid() {
        return ventaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ganancias.ventaId
     *
     * @param ventaid the value for ganancias.ventaId
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setVentaid(Integer ventaid) {
        this.ventaid = ventaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ganancias.totalGanancia
     *
     * @return the value of ganancias.totalGanancia
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public Double getTotalganancia() {
        return totalganancia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ganancias.totalGanancia
     *
     * @param totalganancia the value for ganancias.totalGanancia
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setTotalganancia(Double totalganancia) {
        this.totalganancia = totalganancia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ganancias.fecha
     *
     * @return the value of ganancias.fecha
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ganancias.fecha
     *
     * @param fecha the value for ganancias.fecha
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    
    @Override
    public String toString () {
    	String str = "";
    	str += "idGanancia: " + idganancia + "\n";
    	str += "ventaId: " + ventaid + "\n";
    	str += "totalGanancia: " + totalganancia + "\n";
    	str += "fecha: " + fecha + "\n";
    	return str;
    }
}