package cursoNTecnologias.bd.domain;

public class Marcas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marcas.idMarca
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private Integer idmarca;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marcas.nombreMarca
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    private String nombremarca;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marcas.idMarca
     *
     * @return the value of marcas.idMarca
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public Integer getIdmarca() {
        return idmarca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marcas.idMarca
     *
     * @param idmarca the value for marcas.idMarca
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setIdmarca(Integer idmarca) {
        this.idmarca = idmarca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marcas.nombreMarca
     *
     * @return the value of marcas.nombreMarca
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public String getNombremarca() {
        return nombremarca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marcas.nombreMarca
     *
     * @param nombremarca the value for marcas.nombreMarca
     *
     * @mbg.generated Fri Apr 12 07:54:51 CDT 2019
     */
    public void setNombremarca(String nombremarca) {
        this.nombremarca = nombremarca;
    }
    

	/**
	 * Método que compara si dos objetos son iguales.
	 * 
	 * @param object Objeto a ser comparado.
	 * @return verdadero o falso en la comparación.
	 */
	public boolean equals(Object object) {

		if (!(object instanceof Marcas)) {
			return false;
		}
		Marcas regMarcas = (Marcas) object;
		return (this.idmarca == regMarcas.idmarca);
	}
}